title: María Julissa Barboza Arce
description: <a href="https://www.linkedin.com/in/maría-julissa-barboza-arce-4a9065311" target="_blank">
    <img src="https://cdn-icons-png.flaticon.com/512/174/174857.png" alt="LinkedIn" width="30">
</a>
theme: jekyll-theme-slate
